name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.CI_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H 172.105.182.239 >> ~/.ssh/known_hosts

    - name: Deploy code via SSH
      run: |
        ssh -i ~/.ssh/id_ed25519 root@172.105.182.239 << 'EOF'
        cd ~/cricketapp
        git pull origin main
        systemctl restart cricketapp
        EOF
